---

  - include_tasks: prelim.yml

  - include_tasks: section1.yml
    when: ubu16gsa_section1

  - include_tasks: section2.yml
    when: ubu16gsa_section1

  - include_tasks: section3.yml
    when: ubu16gsa_section1

  - include_tasks: section4.yml
    when: ubu16gsa_section1

  - include_tasks: section5.yml
    when: ubu16gsa_section1

  - include_tasks: section6.yml
    when: ubu16gsa_section1
