- name: "1.8 | Ensure updates, patches, and additional security software are installed"
  become: yes
  apt:
      update_cache: yes
      upgrade: dist
  tags:
      - id_1.8

- name: "1.3.1 | Ensure AIDE is installed"
  apt:
      name: aide
      state: present
  when: ubu16gsa_config_aide == "true"
  tags:
      - id_1.3.1

- name: "1.6.3 | Ensure SELinux or AppArmor are installed"
  apt:
      name: apparmor
      state: present
  when: ubu16gsa_config_apparmor == true
  tags:
      - id_1.6.3_apparmor

- name: "1.6.3 | Ensure SELinux or AppArmor are installed"
  apt:
      name: selinux
      state: present
  when: ubu16gsa_config_selinux == true
  tags:
      - id_1.6.3_selinux

- name: "3.4.1 | Ensure TCP Wrappers is installed"
  apt:
    name: tcpd
    state: present
  tags:
      - id_3.4.1

- name: "3.6 | Ensure firewalld is installed and started | CUSTOM"
  apt:
      name: firewalld
      state: present
  when: ubu16gsa_firewall == "firewalld"
  tags:
      - id_3.6

- name: "3.6.1 | Ensure iptables is installed"
  apt:
      name: iptables
      state: present
  when: ubu16gsa_firewall == "iptables"
  tags:
      - id_3.6.1

- name: "5.3.1 | Ensure password creation requirements are configured"
  apt:
    name: libpam-pwquality
    state: present
